spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters: TokenRelay
      discovery:
        locator:
          enabled: true
      routes[0]:
        id: product-microservice
        uri: lb://PRODUCT-MICROSERVICE
        predicates[0]: Path=/api/products/**, /api/categories/**
      routes[1]:
        id: booking-microservice
        uri: lb://BOOKING-MICROSERVICE
        predicates[0]: Path=/api/bookings/**
    loadbalancer:
      ribbon:
        enabled: false
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/noodlecompany-microservices-realm
        registration:
          spring-cloud-gateway-client:
            authorization-grant-type: authorization_code
            client-id: spring-cloud-gateway-client
            client-secret: Na6rTutANws2w29lcU4NmANEtIdW8ciF
            provider: keycloak
            redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client
            scope: openid

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}